import Navbar from "@/components/Navbar";
import React from "react";
import "../globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="flex flex-col ">
      <div className="flex justify-between items-center">
        <Navbar />
      </div>
      <div className="flex-grow h-screen ">{children}</div>
    </div>
  );
}
